version: '3'

services:
  frontend:
    container_name: frontend
    image: node:20-alpine
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'
    tty: true

  backend:
    container_name: backend
    image: node:20-alpine
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'

  db:
    container_name: db
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - search_app

networks:
  search_app:
    driver: bridge
